# Generated by Django 5.2.3 on 2025-06-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmetrics",
            name="avg_tokens_per_call",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="requestmetrics",
            name="input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="requestmetrics",
            name="llm_calls_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="requestmetrics",
            name="output_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="requestmetrics",
            index=models.Index(
                fields=["llm_calls_count", "timestamp"],
                name="metrics_ser_llm_cal_337f5d_idx",
            ),
        ),
    ]
