# Generated by Django 5.2.3 on 2025-06-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lab_name", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=10)),
                ("semester", models.CharField(max_length=20)),
                ("total_students", models.IntegerField(default=0)),
                ("total_evaluations", models.IntegerField(default=0)),
                ("average_points_lost", models.FloatField(default=0.0)),
                ("common_issues", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("lab_name", "section", "semester")},
            },
        ),
        migrations.CreateModel(
            name="StudentPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=20)),
                ("student_name", models.CharField(max_length=100)),
                ("lab_name", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=10)),
                ("semester", models.CharField(max_length=20)),
                ("total_evaluations", models.IntegerField(default=0)),
                ("total_points_lost", models.IntegerField(default=0)),
                ("average_points_lost", models.FloatField(default=0.0)),
                ("last_evaluation_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("student_id", "lab_name", "section", "semester")},
            },
        ),
    ]
